### ISSUE TITLE
helmfile support

### ISSUE THREAD

**Issue by Diliz** [crumbhole/argocd-lovely-plugin#137]
Hello there!

This plugin is lovely, I was wondering if adding helmfile support would be too big or not?

Helmfile, even if young, is used in some big companies like gitlab, I think it would be really cool to have it available as an option in lovely plugin:
- https://github.com/helmfile/helmfile

It's advantage is that you can use go templating in kustomize files, add subcharts to an existing helm chart, or whatever, it's pretty convenient if you already used to enhance third party helm charts with custom stuff, without using kustomize, or even add default values depending on the environment you're trying to deploy your chart to, etc...

Thanks for reading

**Comment by Joibel** [comment]
Hi, thanks for the kind words. It shouldn't be too difficult to add to lovely, and may even be possible as a plugin to lovely, but - Helmfiles appear to support most use cases that lovely supports directly, so I'm not sure what benefit there would be from having lovely aswell. There are a couple of existing helmfile argocd plugins - https://github.com/travisghansen/argo-cd-helmfile and https://github.com/lucj/argocd-helmfile-plugin. I'm not averse to adding it, just wondering what use cases you have for combining helmfile with lovely's other capabilities.

**Comment by Diliz** [comment]
For my case, I actually have kustomize only, helm only, and helm + kustomize apps on my argocd cluster, but I want to transit to helmfile, so having the possibility to have it in here would simply provide one more way to handle application installation on the cluster, it's more another engine like helm only than using a mixed helm/kustomize thing

I can add a helmfile plugin like you said, and this is what I did, I just wanted to have it all available in one plugin, and lovely one seems to be a good one, I prefer maintaining this one instead of multiple/custom ones :)

**Comment by Joibel** [comment]
This looks like something we can support, I'll try and get it done soone.

**Comment by Joibel** [comment]
0.14.0 is being released, and supports helmfiles. Let me know how you get on with it.

**Comment by Diliz** [comment]
Nice, I'll test this out
