### ISSUE TITLE
Kustomization doesn't work after enabled argocd-lovely-plugin

### ISSUE THREAD

**Issue by vl-kp** [crumbhole/argocd-lovely-plugin#147]
Issue1: Kustomization doesn't work
My repo structure:
```
/test/yamls/dev/kustomization.yaml
/test/yamls/base/kustomization.yaml
/test/yamls/base/deployment.yaml
```

ArgoCD application path set to /test/yamls/dev/, it doesn't work after enable argocd-lovely-plugin, but it's working after i revert

P.s.: argocd config ```kustomize.buildOptions: --load-restrictor LoadRestrictionsNone --enable-helm```

Issue2: if i enabled both helm.valueFiles and plugin, argocd reports multi source error

**Comment by Joibel** [comment]
Issue 2: This is not a lovely plugin problem, ArgoCD doesn't support plugins as well as helm.

**Comment by Joibel** [comment]
Issue 1: You need to enable LOVELY_ALLOW_GITCHECKOUT and read [this](https://github.com/crumbhole/argocd-lovely-plugin/blob/main/doc/allow_git.md) before you do it. Lovely doesn't by default allow access outside the application directory - ArgoCD will stop allowing this too at some point I believe.

**Comment by Joibel** [comment]
You'll have to tell lovely about your kustomize options, it doesn't get told them by ArgoCD through that configuration.
