### ISSUE TITLE
ghcr.io/crumbhole/lovely-vault-plugin has no argocd-vault-plugin binary

### ISSUE THREAD

**Issue by jakuboskera** [crumbhole/argocd-lovely-plugin#213]
I want to use argocd-lovely-plugin along with argocd-vault-plugin. I don't want to use versioned plugin, so I used this image `ghcr.io/crumbhole/lovely-vault-plugin:0.19.4`, however this image has no `argocd-vault-plugin` installed. The image with versioned plugin `ghcr.io/crumbhole/lovely-vault-plugin-ver:0.19.4` this binary have.

From [variations/variations.txt](https://github.com/crumbhole/argocd-lovely-plugin/blob/cd81a2d7b8613590cedd9cb053b726b73a596d66/variations/variations.txt#L6) I can see that the [variations/Dockerfile.nover](https://github.com/crumbhole/argocd-lovely-plugin/blob/main/variations/Dockerfile.nover) is used for building the `ghcr.io/crumbhole/lovely-vault-plugin:0.19.4` image. And this Dockerfile.nover do not install argocd-vault-plugin.

Isn't this some kind of bug or am I doing something wrong?

###  Steps to reproduce

1. Image for versioned plugin which has `argocd-vault-plugin` inside
   ```bash
   docker run --rm --entrypoint "" --platform linux/amd64 \
     ghcr.io/crumbhole/lovely-vault-plugin-ver:0.19.4 \
     which argocd-vault-plugin
   ```

   output

   ```bash
   /usr/local/bin/argocd-vault-plugin
   ```

1. Image for unversioned plugin which has no `argocd-vault-plugin` inside
   ```bash
   docker run --rm --entrypoint "" --platform linux/amd64 \
     ghcr.io/crumbhole/lovely-vault-plugin:0.19.4 \
     which argocd-vault-plugin
   ```

   output

   ```bash
   
   ```

**Comment by Joibel** [comment]
0.19.6 is out and should work now
```
$ docker run --rm --entrypoint "" --platform linux/amd64 \
  ghcr.io/crumbhole/lovely-vault-plugin:0.19.6 \
  which argocd-vault-plugin
...
/usr/local/bin/argocd-vault-plugin
```

**Comment by jakuboskera** [comment]
confirm, thanks for fast fix!
