### ISSUE TITLE
argocd-vault-plugin container includes invalid binary

### ISSUE THREAD

**Issue by Yeradon** [crumbhole/argocd-lovely-plugin#235]
The recent builds of the argocd-vault-plugin container don't include the binary of argocd-vault-plugin. Thus the plugin fails with the following error message:
```level=error msg="`argocd-lovely-plugin` failed exit status 1: 2023/07/30 11:53:45 exit status 127: /usr/local/bin/argocd-vault-plugin: line 1: Not: command not found" execID=36c50```

I checked the most recent image and the image with version tag 0.19.7.
I suspect this to be because of the version parameter in the Dockerfile, which is prefixed with a `v` while the download url excepts a version without prefix.

**Comment by tico24** [comment]
Fixed in v0.19.8 (which is baking right now)
