### ISSUE TITLE
CRDs not included in helmfile template processor

### ISSUE THREAD

**Issue by docqube** [crumbhole/argocd-lovely-plugin#313]
Like already brought up for the helm processor in #63, CRDs are also not included when using the helmfile processor. I looked through the [configurable parameters](https://github.com/crumbhole/argocd-lovely-plugin/blob/main/doc/parameter.md) but it seems, that it is currently not possible to define extra parameters for helmfile, like for helm template with the `LOVELY_HELM_TEMPLATE_PARAMS` variable.

Now the CRDs of the loki chart are not included in the lovely plugin output.

I'd suggest either adding the `--include-crds` parameter by default [here](https://github.com/crumbhole/argocd-lovely-plugin/blob/main/pkg/processor/helmfileProcessor.go#L38) (like already done in the helm processor) or by adding a new environment variable like `LOVELY_HELMFILE_TEMPLATE_PARAMS` where you can define your own parameters needed for your use-case. I'm happy to support with the implementation here.

As a temporary fix I have overwritten the used helmfile executable using the variable `LOVELY_HELMFILE_PATH` set to `/home/argocd/scripts/helmfile.sh`. Here is the `helmfile.sh` content:

```bash
#!/usr/bin/env bash
set -eu
helmfile template --include-crds
```

**Comment by Joibel** [comment]
Yeah, this is all good stuff. I've raised a PR to fix it.

**Comment by docqube** [comment]
@Joibel thanks a lot! Next time, I'll open a PR directly
