### ISSUE TITLE
Remove argocd-cm vestiges from installation examples

### ISSUE THREAD

**Issue by joebowbeer** [crumbhole/argocd-lovely-plugin#362]
The empty argo-cm patches should be removed from the two installation examples:

https://github.com/crumbhole/argocd-lovely-plugin/blob/main/examples/installation/argocd-sidecar/argo-cm.yaml

They are remnants from a bygone implementation and no longer serve a purpose.

**Comment by tico24** [comment]
They serve the purpose of stopping people from blindly putting this into production (hence the security goose banner)

**Comment by tico24** [comment]
The argocd installation being stuck on 2.7 is wrong though. I'll need to look into that.

**Comment by joebowbeer** [comment]
To me, they look like they are updating argocd-cm, support for which was removed in ArgoCD 2.4

**Comment by tico24** [comment]
The example is correct, it's demonstrating the CMP sidecar plugin.

**Comment by joebowbeer** [comment]
The example is correct except that it modifies argocd-cm, which is something that has been discouraged, for any purpose, for a long time.

This confused me into thinking that it contained vestiges of the pre-2.4 pattern that was removed in 2.8, but in fact this modification is just meant as an advisory.

To avoid confusion, I suggest finding a different way to add the advisory.

**Comment by tico24** [comment]
Modifying the argocd cm is absolutely not discouraged. It's a configmap for configuring argocd things.

**Comment by joebowbeer** [comment]
I think the trend is to move away from argocd-cm and move to labels or other means.

This trend is exhibited in:
1. Removal of repo config from argocd-cm
2. Removal of CMP config from argocd-cm

To be clear, in case there's any confusion, I think this modification to argocd-cm is causing more confusion than benefot.
