### ISSUE TITLE
Provide helmwave support

### ISSUE THREAD

**Issue by zhilyaev** [crumbhole/argocd-lovely-plugin#489]
Sure! A little info about Helmwave:
🌊 Helmwave is a pioneer in management helm chart.
It is a part of [CNCF landscape](https://landscape.cncf.io/?selected=helmwave&item=app-definition-and-development--continuous-integration-delivery--helmwave). Helmwave has up to ~600 stars on GitHub and continues to grow, uniting engineers across the world.  

Our community has asked to make an integration with gitops.
Helmwave could mention `argocd-lovely-plugin` in the documentation as a workaround for argocd community.
So that’s why we’ve created this PR #486  for the beginning. If you suggest other options - please guide us through them.

**Comment by zhilyaev** [comment]
`helmwave build`  command will generate plandir in `.helmwave/manifests/$release@$ns.yml` format. Argocd should use these manifests to apply.

helmwave also supports 2 engines for [templating] https://docs.helmwave.app/0.36.x/tpl/ values

**Comment by Joibel** [comment]
Closing as stale
