### ISSUE TITLE
Not compatible with argocd v2.2.0?

### ISSUE THREAD

**Issue by tico24** [crumbhole/argocd-lovely-plugin#5]
After upgrading to v2.2.0, any application using argocd-lovely-plugin goes into an `unknown` sync state with no obvious way of recovering.

Raised this ticket to track any troubleshooting, rca and/or fixing.

**Comment by Joibel** [comment]
Lovely doesn't yet support ArgoCD's new plugin model. I haven't looked up whether the old model is still supported.

**Comment by tico24** [comment]
Just to add an update. The old model appears to still be supported. I have it working with argocd v2.2.1

I *think* the issue boils down to the upgrade from argocd 2.1 to 2.2 doesn't re-spin the various redis cash pods, which causes some sort of internal caching issue. Shooting all the pods seems to get everything working again.
