### ISSUE TITLE
Lovely should learn how to render helm charts with correct Capabilities

### ISSUE THREAD

**Issue by Joibel** [crumbhole/argocd-lovely-plugin#57]
@tico24 discovered that ArgoCD does this correctly now

**Comment by martijnvdp** [comment]
Looks like these are already available as environment vars:

KUBE_VERSION - the version of kubernetes
KUBE_API_VERSIONS = the version of kubernetes API

https://argo-cd.readthedocs.io/en/stable/user-guide/build-environment/

so this would might work better  `--kube-version os.Getenv(`KUBE_VERSION`)`

**Comment by Joibel** [comment]
Closed by #80
