### ISSUE TITLE
Additional Kustomize Args

### ISSUE THREAD

**Issue by wmiller112** [crumbhole/argocd-lovely-plugin#59]
Curious how you'd recommend adding additional args to kustomize such as `--load-restrictor LoadRestrictionsNone`? Attempting to install a chart from local, and can't get it to work unless the /chart is inside the kustomize directory. I see `--helm-enabled` is set [here](https://github.com/crumbhole/argocd-lovely-plugin/blob/main/kustomizeProcessor.go#L76), and we're given the option to provide a path to a different kustomize binary. Would it be possible to use another plugin instead of pointing to a binary? Already have a kustomize plugin with the necessary options set. Otherwise maybe some way to use the argo-cm `kustomize.buildOptions`?

**Comment by Joibel** [comment]
This sounds like a good idea, I'll put together a PR to fix it this week at some point. I'm not sure we can (or should even if we can) get at argo-cm's options, so it'll probably have to be an environment variable, but I'll have a look.

**Comment by Joibel** [comment]
This is fixed in the code. For some reason github release actions aren't firing, so it hasn't built you a fixed version.

**Comment by Joibel** [comment]
0.6.3 is out with this. See LOVELY_KUSTOMIZE_PARAMS.
Note that escaping the application path may well not work for you due to restrictions in ArgoCD which lovely doesn't violate. It depends whether what you're trying to do is within the same `application` or not.
