### ISSUE TITLE
CRDs not included in Helm template

### ISSUE THREAD

**Issue by paveq** [crumbhole/argocd-lovely-plugin#63]
Helm template call should to include flag `--include-crds` in order for Helm to generate custom resource definitions during templating, otherwise CRD's will be missing from output. This is relevant when using lovely-plugin to install cluster addons such as kube-prometheus-stack.

**Comment by Joibel** [comment]
0.6.0 is being built with this change in for you.
Thanks for fixing it, great to have a new contributor.
