### ISSUE TITLE
Make this available as a Config Management Plugin sidecar

### ISSUE THREAD

**Issue by Joibel** [crumbhole/argocd-lovely-plugin#73]
ArgoCD 2.6 will drop support for the currently documented way we run this. We may need to provide various dependencies inside our container.

**Comment by tico24** [comment]
The CI is now in place to handle this, we just need to work on passing vars better.

**Comment by Joibel** [comment]
Which env vars are not exposed as params which should be?

**Comment by tico24** [comment]
They are all exposed, they are just not defaulted. So now that I've typed this, I've realised this is an end-user problem and so I'll be quiet now.
