### ISSUE TITLE
BUG: Alphabetical order breaks rendering

### ISSUE THREAD

**Issue by hawkesn** [crumbhole/argocd-lovely-plugin#75]
Using the latest stable version of argocd-lovely-plugin.

WIth a repo structure like the following:
my-cluster (folder):
  - chart (folder containing a Chart.yaml and values.yaml)
  - d.yaml
  - e.yaml
  - kustomization.yaml
  
  
This works without issue. 

However, if you have a repo like this:

my-cluster (folder):
  - chart (folder containing a Chart.yaml and values.yaml)
  - b.yaml
  - e.yaml
  - kustomization.yaml

It will ONLY render the b and e and it won't render the helm chart.

**Comment by Joibel** [comment]
The second behaviour is the correct one, the first is a bug. It should not render subfolders of folders with yaml in them. I'll attempt to produce a fix at some point.
If you are trying to kustomize the chart they should all be in a folder together.
If you're not then they should be in two separate subfolders.

**Comment by hawkesn** [comment]
Gotcha, I placed them in two separate folders and it worked as expected:

my-cluster (folder):
- chart (folder containing a Chart.yaml and values.yaml)
- manifests (folder containing e.yaml, d.yaml and no kustomization.yaml)

**Comment by Joibel** [comment]
It's still a good bug to find, thanks for reporting it

**Comment by Joibel** [comment]
This is now fixed on master, but unreleased.
