### ISSUE TITLE
Security Goose says: This is a demo installation for the argocd-lovely-plugin. Not for production use.

### ISSUE THREAD

**Issue by gabrielfsousa** [crumbhole/argocd-lovely-plugin#82]
is the argocd-lovely-plugin ready for production ?

**Comment by tico24** [comment]
Of course. The example deployment you reference is not a production deployment of argocd.

**Comment by gabrielfsousa** [comment]
how i install in production ?

**Comment by tico24** [comment]
Exactly how it shows you in the demo. You just need to understand how to make argocd production-ready for your environment. That's out of scope for this plugin.
