### ISSUE TITLE
local Dependencies no longer work after update to 0.13

### ISSUE THREAD

**Issue by astephanh** [crumbhole/argocd-lovely-plugin#96]
I used to work around the private Helm Repo Problem by downloading the chart and include it into the ArgcoCD Repo. But this won't work anymore after updating from 0.7. 

## Version Matrix

| version | success |
|---------|---------|
| 0.7.0   | true    |
| 0.8.0   | true    |
| 0.9.0   | true    |
| 0.10.0  | true    |
| 0.11.0  | false   |
| 0.12.0  | false   |
| 0.13.0  | false   |

## build binary
```sh
make build/argocd-lovely-plugin
```

## create helm chart
```sh
cd examples/multiple-helm-charts/charts/chart2/charts
mkdir charts
helm create charts/hello-world
```
## remove repository
```sh
sed -i '/repository/d' Chart.yaml
```

## run  plugin
```sh
ARGOCD_APP_NAME=foo ../../../../build/argocd-lovely-plugin
```

## Result
- 0.7.0
```txt
ARGOCD_APP_NAME=foo ../../../../build/argocd-lovely-plugin | head
---
# Source: hello-world/charts/hello-world/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: foo-hello-world
  labels:
    helm.sh/chart: hello-world-0.1.0
    app.kubernetes.io/name: hello-world
    app.kubernetes.io/instance: foo
```
- 0.13.0
```txt
ARGOCD_APP_NAME=foo ../../../../build/argocd-lovely-plugin
2023/01/18 11:52:37 exit status 1: Error: could not find protocol handler for:
```

**Comment by Joibel** [comment]
A release 0.13.2 is cooking in github which should address your issue. Reopen if it doesn't.
